### PR TITLE
Remove LICENSE

### PR DESCRIPTION
**Pull request by nikhita**
Addresses https://github.com/kubernetes/kubernetes/issues/54398.

The `README.md` is already present in staging and is not authoritative here.

/cc @sttts

### CODE REVIEW

**Comment by DirectXMan12** [comment]
do we need to wait until the corresponding PR merges the changes to staging?

**Comment by sttts** [comment]
@DirectXMan12 technically no. Only downside: no LICENSE file until we have created new branches to publish and @eparis has run the script again to do the actual push.

**Comment by DirectXMan12** [comment]
I'd prefer not to be missing a license for any significant period of time, but if you anticipate this'll go fairly quickly, I'll merge it now.

**Comment by sttts** [comment]
Will synchronize this with @eparis and the 1.8.2 tag. Eric can merge as well. Then we minimize that time.

**Comment by sttts** [comment]
No patience :-)

**Comment by DirectXMan12** [comment]
heh, whoops, I misunderstood your comment ;-)

**Comment by sttts** [comment]
@DirectXMan12 no problem, trying to get @eparis to merge the other PRs for the other repos. If you happen to be at the same place, tell him how easy this is :)

**Pull request merged**
